spring:
  profiles:
    active: local
  jpa:
     hibernate:
       ddl-auto: create-drop
     show-sql: true
     properties:
       hibernate:
         format_sql: true
  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
     username: sa
     password: sa
     initialization-mode: always
  h2:
     console:
       enabled: true